#!/usr/bin/env python3
"""YouTube Cookie 导出器 — Playwright 独立 Profile 导出 YouTube 登录态。

用法:
    python3 export_cookies.py                    # 有头模式: 打开浏览器让你登录（仅首次需要）
    python3 export_cookies.py --headless         # 无头模式: 复用已保存的登录态
    
原理:
    使用独立的 Playwright profile（不影响你正在运行的 Chrome），
    首次 headful 登录一次后，后续 headless 直接复用。
"""
import argparse
import json
import os
import shutil
import sys
from pathlib import Path

from playwright.sync_api import sync_playwright

# 项目根目录
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Playwright 独立 profile 路径（不影响系统 Chrome）
PW_PROFILE = os.path.join(BASE_DIR, ".pw_profile")

# 默认输出
DEFAULT_OUT = os.path.join(BASE_DIR, "cookies.txt")


def export_cookies(output: str = DEFAULT_OUT, headless: bool = False) -> bool:
    """导出 YouTube cookies 为 Netscape 格式（yt-dlp 兼容）。"""
    os.makedirs(PW_PROFILE, exist_ok=True)

    with sync_playwright() as p:
        print(f"[启动] Chromium (headless={headless})...")
        try:
            ctx = p.chromium.launch_persistent_context(
                user_data_dir=PW_PROFILE,
                headless=headless,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--no-first-run",
                    "--no-default-browser-check",
                    "--no-sandbox",
                ],
                accept_downloads=False,
            )
        except Exception as e:
            print(f"[错误] 启动浏览器失败: {e}", file=sys.stderr)
            return False

        try:
            page = ctx.new_page()
            page.goto("https://www.youtube.com/", wait_until="domcontentloaded", timeout=30000)

            # 检查是否已登录
            logged_in = False
            try:
                page.wait_for_selector("#avatar-btn, yt-img-shadow#avatar img", timeout=5000)
                logged_in = True
                print("[✓] 已检测到 YouTube 登录态")
            except Exception:
                pass

            if not logged_in:
                if headless:
                    print("[失败] 无登录态且为 headless 模式，无法交互登录", file=sys.stderr)
                    print("[提示] 请先运行 'python3 export_cookies.py'（不加 --headless）手动登录", file=sys.stderr)
                    return False
                else:
                    print("\n" + "=" * 50)
                    print("  ⚠️  请在打开的浏览器窗口中登录 YouTube")
                    print("  登录完成后，回到终端按 Enter 继续")
                    print("=" * 50 + "\n")
                    input()
                    # 登录后刷新页面确认
                    page.goto("https://www.youtube.com/", wait_until="domcontentloaded", timeout=30000)

            # 访问一个具体视频页面确保 cookies 完整
            page.goto("https://www.youtube.com/watch?v=dQw4w9WgXcQ", wait_until="domcontentloaded", timeout=30000)
            page.wait_for_timeout(2000)

            # 导出 cookies
            cookies = ctx.cookies()
            yt_cookies = [c for c in cookies
                          if "youtube" in c.get("domain", "") or "google" in c.get("domain", "")]

            if not yt_cookies:
                print("[警告] 未找到 YouTube/Google cookies")
                return False

            # Netscape 格式
            with open(output, "w") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# Generated by Video2Text export_cookies.py\n")
                f.write("# YouTube cookies extracted via Playwright\n\n")
                for c in yt_cookies:
                    domain = c.get("domain", "")
                    flag = "TRUE" if domain.startswith(".") else "FALSE"
                    path = c.get("path", "/")
                    secure = "TRUE" if c.get("secure", False) else "FALSE"
                    expires = str(int(c.get("expires", -1))) if c.get("expires", -1) >= 0 else "0"
                    name = c.get("name", "")
                    value = c.get("value", "")
                    f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

            print(f"[✓] 已导出 {len(yt_cookies)} 个 YouTube cookies → {output}")
            return True

        finally:
            ctx.close()


def check_cookies_valid(path: str = DEFAULT_OUT) -> bool:
    """检查 cookies.txt 是否存在且非空。"""
    return os.path.isfile(path) and os.path.getsize(path) > 100


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="导出 YouTube cookies 供 yt-dlp 使用")
    ap.add_argument("--headless", action="store_true", help="无头模式（已有登录态时使用）")
    ap.add_argument("--out", default=DEFAULT_OUT, help=f"输出路径 (默认: {DEFAULT_OUT})")
    ap.add_argument("--check", action="store_true", help="仅检查 cookies 是否有效")
    args = ap.parse_args()

    if args.check:
        ok = check_cookies_valid(args.out)
        print(f"cookies {'有效' if ok else '不存在/无效'}: {args.out}")
        sys.exit(0 if ok else 1)

    ok = export_cookies(output=args.out, headless=args.headless)
    sys.exit(0 if ok else 1)